### ISSUE TITLE
not working anymore on Gnome 3.22.2 / Debian 9.6

### ISSUE THREAD

**Issue by DanScharon** [mpdeimos/gnome-shell-remove-dropdown-arrows#10]
after the recent update, an error is thrown upon activation

**Comment by dmke** [comment]
Same here. In `/var/log/messages`, these lines appear after upgrading/installing the latest version:

```log
Jan 25 16:17:10 dm org.gnome.Shell.desktop[2033]: Archive:  /tmp/UG30VZ.shell-extension.zip
Jan 25 16:17:10 dm org.gnome.Shell.desktop[2033]:   inflating: /home/dm/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/README.md
Jan 25 16:17:10 dm org.gnome.Shell.desktop[2033]:   inflating: /home/dm/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/extension.js
Jan 25 16:17:10 dm org.gnome.Shell.desktop[2033]:   inflating: /home/dm/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/LICENSE
Jan 25 16:17:10 dm org.gnome.Shell.desktop[2033]:  extracting: /home/dm/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/metadata.json
Jan 25 16:17:10 dm gnome-shell[2033]: JS LOG: Extension "remove-dropdown-arrows@mpdeimos.com" had error: TypeError: children.map(...).includes is not a function
```

**Comment by dmke** [comment]
These seem to be the culprit(s):

- https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows/commit/516402d676aa5d6d4140c1896790543158988bfb#diff-06f1274e40de25abda72d812b1cce86aR77
- https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows/commit/516402d676aa5d6d4140c1896790543158988bfb#diff-06f1274e40de25abda72d812b1cce86aR85

N.B., these are equivalent:

```js
foo.includes(bar)
foo.indexOf(bar) >= 0
```

**Comment by mpdeimos** [comment]
I don't have a 3.22 test env, so I'm not sure if this is the only incompatibility.

Does it work if you replace includes w/ indexOf?

**Comment by dmke** [comment]
Yes, the extension works fine after replacing the two occurrences of the `includes` function.

**Comment by mpdeimos** [comment]
Thanks for testing. Drafted a new release and pushed it to GSE website.
