### ISSUE TITLE
Fail to install on Ubuntu 19.04

### ISSUE THREAD

**Issue by Roboe** [mpdeimos/gnome-shell-remove-dropdown-arrows#13]
After installing latest two updates (yesterday and today) from extensions.gnome.org, the extension doesn't work and shows an `error`. It was working fine before that.

The error is `ReferenceError: Clutter is not defined`. [Log is attached](https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows/files/3625187/2019-10-18_09-54-03_log.txt).
Tried to uninstall and reinstall, just in case.

I'm running updated Ubuntu 19.04 with Gnome 3.32.1 (as stated in Configuration &rarr; About):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by AlexGluck** [comment]
+1 Same error
Fedora 30, Gnome 3.32.2

**Comment by Roboe** [comment]
Aaaand same error in Debian GNU/Linux 10 «buster», up-to-date, Gnome 3.**30**.2

**Comment by mpdeimos** [comment]
Thanks for taking the time reporting an error. I actually aimed to fix that error in v13.
can you let me know whether

~$ cat $HOME/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/extension.js | grep Clutter

yields:

const Clutter = imports.gi.Clutter;
    let panelActor = Main.panel instanceof Clutter.Actor ? Main.panel : Main.panel.actor;

Thanks
-Martin

**Comment by Roboe** [comment]
Yep, it does:

```
$ cat $HOME/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/extension.js | grep Clutter
const Clutter = imports.gi.Clutter;
    let panelActor = Main.panel instanceof Clutter.Actor ? Main.panel : Main.panel.actor;
```

**Comment by Roboe** [comment]
Whoops, I noticed it's working fine now in my Ubuntu 19.04 machine. Maybe a reboot was necessary, for some weird reason? :thinking: 

P.S.: It's also working on my Debian 10 machine.

**Comment by Roboe** [comment]
Recent comment on extensions.gnome.org confirm my theory:

> Donkeehot
>
> Stopped working after last update. Arch linux. Gnome 3.32.2.
> 3 days ago
>
> Sorry for false report. It works just fine after restart, thank you :)
> 2 days ago

> Boricua
>
> Fixed indeed for Fedora 30. Installing the latest update and a logout/login did the trick. Very much appreciated.

I'm closing the issue, then. Thank you, @mpdeimos!
