### ISSUE TITLE
Clipboard Indicator shows the dropdown arrow now.

### ISSUE THREAD

**Issue by simonbcn** [mpdeimos/gnome-shell-remove-dropdown-arrows#9]
```
Arch Linux
GNOME Shell 3.28.1
```

[Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/) shows the dropdown arrow with last version, before it worked. 
If I disable/enable this extension or _Clipboard_ extension, it works. But when I enter in gnome session, it shows it.

**Comment by P1zz4br0etch3n** [comment]
Same here for [Places Status Indicator](https://extensions.gnome.org/extension/8/places-status-indicator/) on Ubuntu 18.04 with same shell version

**Comment by mpdeimos** [comment]
@simonbcn I can reproduce with the Cipboard Indicator. Will have a look why this no longer works (some larger parts of the code have been rewritten to support other extension).

@P1zz4br0etch3n I cannot reproduce with the Places Status Indicator. Is this extension installed per default? Can you let me know the exact version (for me `cat /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/metadata.json`)? What happens if you toggle remove dropdown errors or the other extension on/off?

**Comment by simonbcn** [comment]
_Places Status Indicator_ works well to me.

**Comment by P1zz4br0etch3n** [comment]
I think the extension was pre-installed on Ubuntu GNOME 16.04 before I upgraded to 18.04. But I updated it from extensions.gnome.org, so I think the one from my home folder is actually beeing used.

The arrow is displayed on system start. When I toggle _Remove Dropdown Arrows_ it disappears. When I toggle the _Places Menu_ after that, its arrow reappears. When I toggle it before, nothing changes.

Here are my outputs:
```
~$ cat .local/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Add a menu for quickly navigating places in the system.\nThis extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.", 
  "extension-id": "places-menu", 
  "gettext-domain": "gnome-shell-extensions", 
  "name": "Places Status Indicator", 
  "settings-schema": "org.gnome.shell.extensions.places-menu", 
  "shell-version": [
    "3.28"
  ], 
  "url": "https://gitlab.gnome.org/GNOME/gnome-shell-extensions", 
  "uuid": "places-menu@gnome-shell-extensions.gcampax.github.com", 
  "version": 40

~$ cat /usr/share/gnome-shell/extensions/places-menu@gnome-shll-extensions.gcampax.github.com/metadata.json
{
"extension-id": "places-menu",
"uuid": "places-menu@gnome-shell-extensions.gcampax.github.com",
"settings-schema": "org.gnome.shell.extensions.places-menu",
"gettext-domain": "gnome-shell-extensions",
"name": "Places Status Indicator",
"description": "Add a menu for quickly navigating places in the system.\nThis extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.",
"shell-version": [ "3.28" ],
"url": "https://gitlab.gnome.org/GNOME/gnome-shell-extensions"
}

```

**Comment by simonbcn** [comment]
@P1zz4br0etch3n Wouldn't it be better if you uninstalled the system extension?
The gnome extensions is better to install in each user folder.

**Comment by P1zz4br0etch3n** [comment]
I can do that, but it doesn't matter cause the user extension is used prior to the system extension since it is a newer version. But thank you anyway.

**Comment by P1zz4br0etch3n** [comment]
I just noticed that this issue doesn't appear on my laptop although all versions are the same (extensions, gnome-shell and ubuntu). If I have more time I try to figure out what causes the problem.

**Comment by P1zz4br0etch3n** [comment]
For some reason the issue has gone for me now. I just played a little bit with the sources of the Places Menu and reverted all of my changes as it didn't work. I don't know why it works now. But for me this issue can be closed.

**Comment by mpdeimos** [comment]
I've debugged the issue. Seems that the Clipboard extension is not adding its button in the default location but at position `1`. Fixed the problem and uploaded a new release to Gnome Extensions and [GitHub](https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows/releases/tag/v10).

**Comment by walkie** [comment]
I'm seeing this issue again on Fedora 32. After logging in or after restarting gnome-shell, the icon for the "clipboard indicator" extension still has a dropdown arrow. 

As before, stopping and restarting the "remove dropdown arrows" extension removes the arrow from the clipboard icon.
